# Project Setting
org.gradle.daemon=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096M

# Minecraft
minecraftVersion=1.20.2
mappingsVersion=1.20.2+build.4
fabricVersion=0.91.6+1.20.2

# Global Setting
loomVersion=1.10-SNAPSHOT
loaderVersion=0.16.13
javaVersion=21
kotlinVersion=2.1.10
fabricLanguageKotlinVersion=1.13.1+kotlin.2.1.10