# Project Setting
org.gradle.daemon=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096M

# Minecraft
minecraftVersion=1.21.5
mappingsVersion=1.21.5+build.1
fabricVersion=0.119.9+1.21.5

# Global Setting
loomVersion=1.10-SNAPSHOT
loaderVersion=0.16.13
javaVersion=21
kotlinVersion=2.1.10
fabricLanguageKotlinVersion=1.13.1+kotlin.2.1.10