[versions]
kotlin = "2.2.21"
loom = "1.13-SNAPSHOT"
shadowJar = "9.2.2"

minecraft = "1.21.10"
yarn = "1.21.10+build.2"
fabric-api = "0.138.3+1.21.10"
fabric-loader = "0.17.3"
fabric-kotlin = "1.13.6+kotlin.2.2.20"

akkaradb = "0.2.0"
akkara-plugin = "0.1.0"
langMan-core = "2.0.3"
langMan-yaml = "2.0.1"
yacla-core = "3.0.0"
yacla-yaml = "3.0.0"
cask = "1.0.0"

jda = "6.1.1"
yaml = "2.5"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadowJar" }
akkara = { id = "dev.swiftstorm.akkaradb-plugin", version.ref = "akkara-plugin" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

langman-core = { module = "net.ririfa:langman-core", version.ref = "langMan-core" }
langman-yaml = { module = "net.ririfa:langman-ext.yaml", version.ref = "langMan-yaml" }
yacla-core = { module = "net.ririfa:yacla-core", version.ref = "yacla-core" }
yacla-yaml = { module = "net.ririfa:yacla-yaml", version.ref = "yacla-yaml" }
cask = { module = "net.ririfa:cask", version.ref = "cask" }

jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "yaml" }