[versions]
kotlin="2.1.20"
loom="1.10-SNAPSHOT"
shadowJar="8.1.1"

minecraft="1.21.5"
fabric-yarn="1.21.5+build.1"
fabric-loader="0.16.13"
fabric-api="0.120.0+1.21.5"
fabric-kotlin="1.13.2+kotlin.2.1.20"

jda = "5.4.0"
yaml="2.4"
langman="1.4.4"
exposed="0.61.0"
gson = "2.13.0"

[plugins]
kotlin={ id="org.jetbrains.kotlin.jvm", version.ref="kotlin" }
loom={ id="fabric-loom", version.ref="loom" }
shadowJar={ id="com.github.johnrengelman.shadow", version.ref="shadowJar" }

[libraries]
minecraft={ module="com.mojang:minecraft", version.ref="minecraft" }
fabric-yarn={ module="net.fabricmc:yarn", version.ref="fabric-yarn" }
fabric-loader={ module="net.fabricmc:fabric-loader", version.ref="fabric-loader" }
fabric-api={ module="net.fabricmc.fabric-api:fabric-api", version.ref="fabric-api" }
fabric-kotlin={ module="net.fabricmc:fabric-language-kotlin", version.ref="fabric-kotlin" }

jda={ module="net.dv8tion:JDA", version.ref="jda" }
yaml={ module="org.yaml:snakeyaml", version.ref="yaml" }
langman={ module="net.ririfa:langman", version.ref="langman" }
exposed-core={ module="org.jetbrains.exposed:exposed-core", version.ref="exposed" }
exposed-dao={ module="org.jetbrains.exposed:exposed-dao", version.ref="exposed" }
exposed-jdbc={ module="org.jetbrains.exposed:exposed-jdbc", version.ref="exposed" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
fabrics = ["fabric-loader", "fabric-api", "fabric-kotlin"]
fabricord = ["yaml", "langman", "exposed-core", "exposed-dao", "exposed-jdbc", "gson", "jda"]