[versions]
kotlin = "2.3.20"
shadow = "9.6.1"

yacla-core = "4.1.1"
yacla-yaml = "4.1.0"

langman-core = "2.1.0"
langman-yaml = "2.1.0"

snakeyaml = "2.6"

jda = "6.7.0"
sqlite-jdbc = "3.53.4.0"

[libraries]
yacla-core = { module = "net.ririfa:yacla-core", version.ref = "yacla-core" }
yacla-yaml = { module = "net.ririfa:yacla-yaml", version.ref = "yacla-yaml" }

langman-core = { module = "net.ririfa:langman-core" , version.ref = "langman-core" }
langman-yaml = { module = "net.ririfa:langman-ext.yaml", version.ref = "langman-yaml" }

yaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
